export declare const getTransData: (columns: any, data: any) => any[];
export declare const transColumnsToObj: (columns: any) => {};
export declare const getColDef: (columnDefs: any, fieldName: any) => {};
export declare const getValueGetter: (params: any) => any;
export declare const getInitValueFormatter: (params: any) => any;
export declare const getValueRender: (params: any) => any;
export declare const getEditable: (params: any) => any;
export declare const getDiffProps: (srcObj: any, targetObj: any) => {};
export declare const getOriginData: (data: any) => any;
